version: '3.8'

services:
  db:
    env_file:
      - path: .env
        required: true
    image: postgres:15
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: keycloak

  keycloak:
    env_file:
      - path: .env
        required: true
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PG_PASSWORD: ${PG_PASSWORD}
        KC_HOSTNAME: ${KC_HOSTNAME}
    ports:
      - "127.0.0.1:8080:8080"
    restart: always
    environment:
      KEYCLOAK_ADMIN: ${KC_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KC_PASSWORD}
      KC_DB_URL: jdbc:postgresql://db/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: ${PG_PASSWORD}
      KC_HOSTNAME: ${KC_HOSTNAME}

volumes:
  keycloak-db-data:
